language: node_js
sudo: false
node_js:
  - 8
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install: yarn install --frozen-lockfile
script:
  - yarn run lint
  - lerna bootstrap --ignore=demos
  - lerna run prepublish --ignore=demos
  - lerna run pretest --ignore=demos
  - lerna run test --ignore=demos --concurrency=1
  - yarn run tsc
  - lerna run prepublish --ignore=demos
