language: node_js
sudo: false
node_js:
  - 6
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn install --frozen-lockfile
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - lerna bootstrap --ignore={benchmarks,demos} -- --frozen-lockfile
  - lerna run pretest --ignore={benchmarks,demos}
  - lerna run test --ignore={benchmarks,demos} --concurrency=1
  - yarn run tsc
  - lerna run prepublish --ignore={benchmarks,demos}
after_script: greenkeeper-lockfile-upload
