name: Assert Flow Message

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flow-version: [0.110.0, 0.111.3, 0.112.0, 0.113.0, 0.115.0, 0.116.1, 0.117]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: yarn bootstrap
    - run: yarn add ${{ matrix.flow-version }}
    - run: yarn lerna run --scope flow-type-tests test
